/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodosimplex;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author diego
 */
public class segundoFrame extends javax.swing.JFrame {

    /**
     * Creates new form segundoFrame
     */
    int numVariables=10;
    int numEcuaciones=10;
    JTextField[] cuadrosZ;
    JTextField[] cuadrosA;
    JTextField[] cuadrosLD;
    JComboBox<String>[] vectorDesigualdades;
    String cadena="";
    String tipoZ;
    
    public segundoFrame() {
        initComponents();
        numEcuaciones=10;
        numVariables=10;
        iniciaTablas();
        actualizaCuadros();
    }
    
    public segundoFrame(int numVariables,int numEcuaciones,String tipoZ){
        initComponents();
        this.tipoZ=tipoZ;
        this.numEcuaciones = numEcuaciones;
        this.numVariables = numVariables;
        iniciaTablas();
        actualizaCuadros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void actualizaCuadros(){
        String cadena="Z: ";
        cadena+=""+tablaZ.getValueAt(0, 0)+"x1";
        for(int i=1;i<numVariables;i++){
            cadena+=" + "+tablaZ.getValueAt(0, i)+"x"+(i+1);
        }
        cadena+="\n\nEcuaciones: \n";
        
        for(int i=0;i<numEcuaciones;i++){
            cadena+="Ec"+(i+1)+": ";
            for(int j=0;j<numVariables;j++){
                cadena+=""+tablaA.getValueAt(i,j)+"x"+(j+1)+" + ";
            }
            cadena+=" "+tablaA.getValueAt(i, 10)+" ";
            cadena+=tablaA.getValueAt(i, 11)+" \n";
        }
        cuadroTipoZ.setText("tipo función: "+tipoZ);
        cuadroEc.setText("Ecuaciones: "+numEcuaciones);
        cuadroVar.setText("variables: "+numVariables);
        TablaDatos.setText(cadena);
    }
    
    private void seleccionEjemplo(){
        limpiaTablas();
        switch(cajaEjemplos.getSelectedIndex()){
            case 0:{
                double[][] matrizA={{5000,4000},{400,500}};
                double vectorZ[]={4500,4500};
                String vectorDesigualdades[]={"<","<"};
                double[] LD={0,6000,600}; //primer valor para Z, otros para matrizA
                insertaEjemplo(matrizA,vectorZ,LD,vectorDesigualdades);
                tipoZ="max";
                break;
            }
            
            
            case 1:{
                double[][] matrizA={{2,2,0},{1,2,4},{1,3,2}};;
                double vectorZ[]={-1000,-6000,-3000};
                String vectorDesigualdades[]={">",">",">"};
                double[] LD={0,20,80,70}; //primer valor para Z, otros para matrizA
                insertaEjemplo(matrizA,vectorZ,LD,vectorDesigualdades);
                tipoZ="min";
                break;
            }
            case 2:{
                tipoZ="min";
                double[][] matrizA={{2,2,0},{1,2,4},{1,3,2}};;
                double vectorZ[]={1000,6000,3000};
                String vectorDesigualdades[]={">",">",">"};
                double[] LD={0,20,80,70}; //primer valor para Z, otros para matrizA
                insertaEjemplo(matrizA,vectorZ,LD,vectorDesigualdades);
                break;
            }
            case 3:{
                tipoZ="max";
                double[][] matrizA={{1,1,1,0,0,0,0,0,0},{0,0,0,1,1,1,0,0,0},{0,0,0,0,0,0,1,1,1},{20,15,12,0,0,0,0,0,0},{0,0,0,20,15,12,0,0,0},{0,0,0,0,0,0,20,15,12},{1,0,0,1,0,0,1,0,0},{0,1,0,0,1,0,0,1,0},{0,0,1,0,0,1,0,0,1}};;
                double vectorZ[]={420,360,300,420,360,300,420,360,300};
                String vectorDesigualdades[]={"<","<","<","<","<","<","<","<","<"};
                double[] LD={0,750,900,450,13000,12000,5000,900,1200,650}; //primer valor para Z, otros para matrizA
                insertaEjemplo(matrizA,vectorZ,LD,vectorDesigualdades);
                break;
            }
            case 4:{
                tipoZ="min";
                double[][] matrizA={{0.5,0.45,0.6,0,0,0},{1,1,1,0,0,0},{1,0,0,1,0,0},{0,1,0,0,1,0},{0,0,1,0,0,1}};;
                double vectorZ[]={3,4,4,6,6,7};
                String vectorDesigualdades[]={">",">","<","<","<"};
                double[] LD={0,2400,5500,2000,4000,5000}; //primer valor para Z, otros para matrizA
                insertaEjemplo(matrizA,vectorZ,LD,vectorDesigualdades);
                break;
            }
            
        }
        
        actualizaCuadros();
}
    
    private void insertaEjemplo(double[][] matrizA,double[] vectorZ,double LD[], String[] vectorDesigualdades){
        numEcuaciones=vectorDesigualdades.length;
        numVariables=vectorZ.length;
        for(int i=0;i<numEcuaciones;i++){
            for(int j=0;j<numVariables;j++){
                tablaA.setValueAt(matrizA[i][j], i, j);
                tablaZ.setValueAt(vectorZ[j], 0, j);
            }
            tablaA.setValueAt(vectorDesigualdades[i], i, 10);
            tablaA.setValueAt(LD[i+1], i, 11);
        }
        
        
    }
    
    
    private void iniciaTablas(){
        
        for(int i=0;i<numVariables;i++){
            for(int j=0;j<numEcuaciones;j++){
                tablaA.setValueAt(0, j, i);
            }
            tablaZ.setValueAt(0, 0, i);
        }
        //JComboBox temporal;
        for(int j=0;j<numEcuaciones;j++){
                //temporal = new javax.swing.JComboBox<>();
                //temporal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">", "=" }));
                tablaA.setValueAt("<", j, 10);
                tablaA.setValueAt(0, j, 11);
                
            }
    }
    
    private void limpiaTablas(){
    
        tablaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10", "{<,>}", "LD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaZ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
}
    
    private void ejecutaMetodo(){
        double[][] matrizA = new double[numEcuaciones][numVariables];
        double vectorZ[] = new double[numVariables];
        String vectorDesigualdades[]=new String[numEcuaciones];
        double[] LD=new double[numEcuaciones+1];
        LD[0]=0;
        
        
        String cadena="";
        Double a;
        for(int i=0;i<numEcuaciones;i++){
            for(int j=0;j<numVariables;j++){
                a=Double.parseDouble(""+tablaA.getValueAt(i, j));
                matrizA[i][j]=a.doubleValue();
                cadena+=" "+a;
            }   
        }
        cadena+="Z: ";
        for(int i=0;i<numVariables;i++){
                a=Double.parseDouble(""+tablaZ.getValueAt(0, i));
                vectorZ[i]=a.doubleValue();
                cadena+=a+" ";
        }
        cadena+="\n";
        for(int j=0;j<numEcuaciones;j++){
                vectorDesigualdades[j]=(String) tablaA.getValueAt(j, 10);
                a=Double.parseDouble(""+tablaA.getValueAt(j, 11));
                LD[j+1]=a.doubleValue();
                cadena+=vectorDesigualdades[j]+" ";
                
        }
        System.out.println(cadena);
        
        String salida;
        Main uno = new Main(matrizA,vectorZ,LD,vectorDesigualdades);
        salida = uno.ejecutaMetodo();
        jTextArea1.setText(salida);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaZ = new javax.swing.JTable();
        cuadroTipoZ = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cuadroVar = new javax.swing.JLabel();
        cuadroEc = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cajaEjemplos = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipo 5 simplex");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel9.setText("Z:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">", "=" }));

        tablaA.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        tablaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10", "{<,>}", "LD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(tablaA);

        tablaZ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaZ);

        cuadroTipoZ.setText("tipoZ: ");

        jButton2.setText("CALCULAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cuadroVar.setText("Variables:");

        cuadroEc.setText("Ecuaciones:");

        jButton3.setText("actualizar datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cajaEjemplos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejemplo 1", "Ejemplo 2", "Ejemplo 2.1", "Ejemplo 3", "Ejemplo 4" }));

        jButton4.setText("poner ejemplo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TablaDatos.setColumns(20);
        TablaDatos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        TablaDatos.setRows(5);
        jScrollPane4.setViewportView(TablaDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuadroEc)
                            .addComponent(cuadroVar)
                            .addComponent(cuadroTipoZ))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cajaEjemplos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(36, 36, 36))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cuadroTipoZ)
                        .addGap(12, 12, 12)
                        .addComponent(cuadroEc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadroVar)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaEjemplos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Aqui aparecera la salida del programa.\n\n-El programa solo tomara en cuenta el numero de variables y ecuaciones previamente establecido, por lo que si se introduce un valor en espacios no validos, simplemente no servira\n\n-Pulsa el boton \"actualizar datos\" para ver que datos entraran a la ejecución del método\n\n-El programa no esta completamente testeado, por lo que puede soltar errores\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(jTextArea1);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel10.setText("Salida:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel1.setText("Método simplex");

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new primerFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ejecutaMetodo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        actualizaCuadros();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        seleccionEjemplo();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void generarZ(){
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TablaDatos;
    private javax.swing.JComboBox<String> cajaEjemplos;
    private javax.swing.JLabel cuadroEc;
    private javax.swing.JLabel cuadroTipoZ;
    private javax.swing.JLabel cuadroVar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaA;
    private javax.swing.JTable tablaZ;
    // End of variables declaration//GEN-END:variables
}
